# 4.8 Grouping Data & Aggregation

## Contents

### 01. Importing libraries
### 02. Importing data
### 03. Grouping data +  Aggregating Data with agg() & transform() + Deriving Columns with loc

## 01. Importing libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

## 02. Importing Data

In [2]:
path = r'C:\Users\Sulo\Desktop\Careerfoundry\11.09.2023 Instacart Basket Analysis'

In [3]:
# Import the pickle file
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_new_columns.pkl'))

## 03. Grouping data +  Aggregating Data with agg() & transform() + Deriving Columns with loc

In [31]:
# Take count of rows and columns
ords_prods_merge.shape

(32404859, 22)

In [32]:
# Show the current data frame
ords_prods_merge.head()

,order_id,user_id,order_amount,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,avg_order,spending_flag,med_days,order_frequency_flag
0,2539329,1,1,2,8,7.0,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.

In [33]:
# Group the deparment_id by the mean order_amount of the whole database
ords_prods_merge.groupby('department_id').agg({'order_amount': ['mean']})

              order_amount
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

## 3) The difference are that more departments show up and the means are different from the subset, because the database his way bigger than the small subset we created and therefore doesn't show the true values of the database.

In [34]:
# Create a max_order column and group it by user_id and the order_amount
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_amount'].transform(np.max)

In [35]:
# Check if it worked
ords_prods_merge.head(15)

,order_id,user_id,order_amount,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,avg_order,spending_flag,med_days,order_frequency_flag
0,2539329,1,1,2,8,7.0,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.

In [36]:
# Create a new column with conditions for loyal, regular and new customers through the max_order value column
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [37]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [38]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [39]:
# Check data consistency 
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [40]:
# Check if creating the column worked
ords_prods_merge.head()

,order_id,user_id,order_amount,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,avg_order,spending_flag,med_days,order_frequency_flag
0,2539329,1,1,2,8,7.0,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.

In [41]:
# Find the basic statistics from the values of the loyalty_flag
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

In [42]:
# Create a new column for average orders and group it by user_id and the mean of prices
ords_prods_merge['avg_order'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [43]:
# Create a new column through the avg order column to determine the spending_flag column and their conditions
ords_prods_merge.loc[ords_prods_merge['avg_order'] >= 10, 'spending_flag'] = 'High spender'

In [44]:
ords_prods_merge.loc[ords_prods_merge['avg_order'] < 10, 'spending_flag'] = 'Low spender'

In [45]:
# Check the data for consistency
ords_prods_merge['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

In [46]:
# Check if the new columns worked
ords_prods_merge.head(50)

,order_id,user_id,order_amount,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,avg_order,spending_flag,med_days,order_frequency_flag
0,2539329,1,1,2,8,7.0,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender,7.0,Frequent customer.
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender,7.0,Frequent customer.
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Average orders,9,New customer,8.372059,Low spender,7.0,Frequent customer.
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,9.0,Mid-range product,Least busy,Most orders,33,Regular customer,7.012683,Low spender,7.0,Frequent customer.
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer.
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer.
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,9.0,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer.
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer.
23,2497897,52,1,1,9,7.0,196,4,0,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
37,3205960,67,1,3,11,7.0,196,1,0,Soda,...,9.0,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.

In [47]:
# Create a new column for median days and group it by user_id and the median of the days since prior order column
ords_prods_merge['med_days'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [48]:
# Create a new column through the med days column to determine the order_frequency_flag column and their conditions
ords_prods_merge.loc[ords_prods_merge['med_days'] > 20, 'order_frequency_flag'] = 'Non-frequent customer.'

In [49]:
ords_prods_merge.loc[(ords_prods_merge['med_days'] <= 20) & (ords_prods_merge['med_days'] > 10), 'order_frequency_flag'] = 'Regular customer.'

In [50]:
ords_prods_merge.loc[ords_prods_merge['med_days'] <= 10, 'order_frequency_flag'] = 'Frequent customer.'

In [51]:
# Check for data consistency
ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

order_frequency_flag
Frequent customer.        22790523
Regular customer.          6927608
Non-frequent customer.     2686728
Name: count, dtype: int64

In [52]:
# Check if the new columns worked
ords_prods_merge.head(50)

,order_id,user_id,order_amount,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_days,busiest_period_of_day_loc,max_order,loyalty_flag,avg_order,spending_flag,med_days,order_frequency_flag
0,2539329,1,1,2,8,7.0,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,10,New customer,6.367797,Low spender,20.0,Regular customer.
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,8.0,Frequent customer.
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender,7.0,Frequent customer.
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,9,New customer,8.372059,Low spender,7.0,Frequent customer.
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Average orders,9,New customer,8.372059,Low spender,7.0,Frequent customer.
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,9.0,Mid-range product,Least busy,Most orders,33,Regular customer,7.012683,Low spender,7.0,Frequent customer.
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer.
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,20,Regular customer,8.137793,Low spender,6.0,Frequent customer.
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,9.0,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer.
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,11,Regular customer,7.444898,Low spender,10.0,Frequent customer.
23,2497897,52,1,1,9,7.0,196,4,0,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,9.0,Mid-range product,Regularly busy,Fewest orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,9.0,Mid-range product,Least busy,Fewest orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0,Frequent customer.
37,3205960,67,1,3,11,7.0,196,1,0,Soda,...,9.0,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,9.0,Mid-range product,Least busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,9.0,Mid-range product,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,9.0,Mid-range product,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0,Frequent customer.

In [53]:
# Export data to pkl
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_merge.pkl'))